version: '3.8'

services:
    web:
        image: my-fastapi-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8004:80"
        volumes:
            - .:/app
        restart: always